### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by samyce** [cartalyst/demo-data-grid#14]
[RuntimeException]                                                                                                                                                            
  Failed to execute git clone --mirror 'https://***:***@github.com/cartalyst/data-grid.git' 
...                                                                                                                                  
  remote: Repository not found.                                                                                                                                                 
  fatal: repository 'https://github.com/cartalyst/data-grid.git/' not found

**Comment by brunogaspar** [comment]
Hey

It seems you don't have Git properly setup to access the private repositories or the user you have on your machine might not match the one that has access to the private repositories.

The main way to set this up is with SSH. You can have a look [here](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/connecting-to-github-with-ssh) for more information.

The other way is by using HTTPS and you need to pass your GitHub username and password during the clone.

Something like this:

```
git clone https://samyce:yourgithubpassword@github.com/cartalyst/data-grid.git
```

As a side note, if you have 2FA enabled, the above will most likely not work and you'll need to use personal access tokens instead, you can read [here](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token) more about personal access tokens.

Hope it helps.

**Comment by brunogaspar** [comment]
Also, as mentioned on the README:

```
To install this demo, firstly you must be a subscriber of Cartalyst's Arsenal.
```

Which means you need to have a paid and active subscription to access the private repository.
